"use client"

import { Inter } from 'next/font/google'
import Header from './component/Header'
import './styles/style.scss'
import Loader from './component/Loader'
import { useEffect, useState } from 'react'
import { Router } from 'next/router'
import Enrich from './component/Enrich'
import Footer from './component/Footer'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const [loader, setLoader] = useState(false);

  Router.events.on('routeChangeStart', () => {
    setLoader(true);
  });
  Router.events.on('routeChangeComplete', () => {
    setLoader(false);
  });

  useEffect(() => {

  }, [loader])

  return (
    <html lang="en">
      {loader && <Loader />}
      {/* <Loader /> */}
      <body className={inter.className}>
        <Header />
        {children}
        <Enrich />
        <Footer  />
      </body>
    </html>
  )
}
